name: sync-releaese-repository-java
author: yuchenxue
description: sync release repository java

inputs:
  repository:
    description: repository to build
    required: true
  release_prefix:
    description: release prefix
    required: true
  github_token:
    description: github token
    required: true
  local_repository:
    description: local repository
    required: true

outputs:
  trigger:
    description: trigger sync release
  upstream_tag:
    description: upstream release tag
  release_tag:
    description: release tag

runs:
  using: node20
  main: index.js
