name: Build Graphite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout local repository
        uses: actions/checkout@v6

      - name: build
        uses: ./.github/workflows/build-action.yml
        with:
          working-path: ./SonaGG/Graphite
          repository: SonaGG/Graphite
          branch: 1.8.9
          java-version: 21
