name: Build LiquidBounce

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: build
        uses: yuchenxue123/builder/.github/actions/build-repository-java@main
        with:
          repository: CCBlueX/LiquidBounce
          branch: nextgen
          java-version: 25