name: Sync Release LiquidBounce
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: check new release
        id: check
        uses: yuchenxue123/builder/.github/actions/check-release@main
        with:
          repository: CCBlueX/LiquidBounce
          release_prefix: lbng
          github_token: ${{ secrets.GITHUB_TOKEN }}
          local_repository: ${{ github.repository }}

      - name: build
        uses: yuchenxue123/builder/.github/actions/build-repository-java@main
        if: steps.check.outputs.trigger == 'true'
        with:
          repository: CCBlueX/LiquidBounce
          branch: ${{ steps.check.outputs.upstream_tag }}
          java-version: 21

      - name: release
        if: steps.check.outputs.trigger == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.check.outputs.release_tag }}
          name: ${{ steps.check.outputs.release_tag }}
          body: |
            该版本是自动构建和释放的
            链接: ${{ steps.check.outputs.upstream_url }}
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
